sudo: required
services:
  - docker
language: perl
perl:
  - "5.24"
  - "5.22"
  - "5.14"
  - "5.10"
  - "5.8"
before_install:
  - tests/docker/phpfpm/build.sh
# command to install dependencies
install:
  - cpanm -n -q --skip-satisfied --installdeps .
  - chmod ugo+x tests/test.sh
# command to run tests
script:
  - tests/test.sh

